CREATE TABLE IF NOT EXISTS podcast_settings (
  organization_id BIGINT UNSIGNED NOT NULL,
  podcast_title VARCHAR(255) NOT NULL,
  podcast_description TEXT NULL,
  podcast_author VARCHAR(255) NULL,
  podcast_language VARCHAR(20) NOT NULL DEFAULT 'de-CH',
  podcast_image_url VARCHAR(1000) NULL,
  ftp_host VARCHAR(255) NOT NULL,
  ftp_port SMALLINT UNSIGNED NOT NULL DEFAULT 21,
  ftp_secure BOOLEAN NOT NULL DEFAULT TRUE,
  ftp_username VARCHAR(255) NOT NULL,
  ftp_password TEXT NOT NULL,
  ftp_password_iv CHAR(24) NOT NULL,
  ftp_password_tag CHAR(32) NOT NULL,
  ftp_directory VARCHAR(1000) NOT NULL DEFAULT '/',
  public_base_url VARCHAR(1000) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (organization_id),
  CONSTRAINT podcast_settings_organization_id_foreign FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS podcast_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  youtube_account_id BIGINT UNSIGNED NOT NULL,
  youtube_video_id VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  start_seconds DECIMAL(10,3) NOT NULL,
  end_seconds DECIMAL(10,3) NOT NULL,
  status ENUM('queued','processing','uploading','published','failed') NOT NULL DEFAULT 'queued',
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  worker_id VARCHAR(100) NULL,
  lease_until TIMESTAMP NULL,
  audio_filename VARCHAR(500) NULL,
  audio_url VARCHAR(1500) NULL,
  audio_bytes BIGINT UNSIGNED NULL,
  duration_seconds INT UNSIGNED NULL,
  error_message TEXT NULL,
  published_at TIMESTAMP NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY podcast_jobs_video_unique (organization_id, youtube_video_id),
  KEY podcast_jobs_status_index (status, created_at),
  CONSTRAINT podcast_jobs_organization_id_foreign FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT podcast_jobs_account_id_foreign FOREIGN KEY (youtube_account_id) REFERENCES youtube_accounts (id) ON DELETE CASCADE,
  CONSTRAINT podcast_jobs_created_by_foreign FOREIGN KEY (created_by) REFERENCES users (id)
);
